apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch-master-key
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: meilisearch-master-key
    creationPolicy: Owner
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: meilisearch-master-key
        property: MEILI_MASTER_KEY
