apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-storage
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  dsm: "10.10.10.9"
  location: "/volume1/pi5k3s"
  mountPermissions: "0755"
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Delete
allowVolumeExpansion: true
