apiVersion: v1
kind: Service
metadata:
  name: promtail-syslog
  namespace: monitoring
spec:
  selector:
    name: promtail
  ports:
    - protocol: TCP
      port: 1514 # The port Syslog-NG will use to send logs
      targetPort: 1514 # Make sure this matches the port Promtail listens to
  type: ClusterIP
