apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:TQqGqh6z633nIxgb1z4gxhDD46vBRTkPS0MGvo5pP0WnDDFSPKIW7GdYdfvisxcl+ovRECDfTwWpUq4uXsV3bnhxua0r0h/UnQ06DcMqhFB00qNX5cqYmyVSPFVbr5aW3MI3IxHUtjx7Oig3Lr7e7bb/IlZTQEimp5Ji70j7n/kPfJVwn0svZaixxRFE4LXzqP3/HcMpvRAftJRObYYCSalIbQU6DgYM72PtYVL8MQRHXn+ntgzds8Jcr5KK82yJ5dazA078iSmXowlu4f9Xre/9Bzcl5XjWaAAscKKhPPSvAFeExIDKDzt7Xuc=,iv:2q6UH96SI+9A6kiGoQd0ShqH1QGhUPoSVpRYcLnNMyI=,tag:+uyi6Y5T5wrNzaEBP1pwpQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1c2eykwtau0ln8yxv6jdq5xl9fvnlh2ytcre3ctf5sx75dseag3pq6mmj4v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb0VoV091RHMxRnNDbC8r
            bFVHMDYzSTJFclBmd0NoQThWM25wY2g0RGdVCkkrZGNyaHA5Q0Jka04rUDZacmRP
            RDRTb3NsVUp2Z2UxdzlDMnBpOUZhclUKLS0tIGNEUjlkSWJhTDljRGs4ZXI4c0Nz
            WXowdGw5VFdZZjFmVnhjazN0Q1MyUjgKMLM3+Q3LIKMQf637QbmDoKzO3S3oPiVp
            W/KAgPRgCJF3mRFrLJaO3m9dv960TEL/ytebHeeoWKvTcSvdxKR0+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T10:58:55Z"
    mac: ENC[AES256_GCM,data:B3/oHOFTRVwwkQs6jG1xfJF4+fgQjjifzeg9uHN9Spx7Dasx8zYqrA6vW0IKkb7Du2HjIlos2mMyALQKDGcuxELFs8KAK1RdG6uQIS7xV5J2b99IhiBrRqQPdImA7donRsdCXjj2RJW2HZNarzpZRTib2grWrFihwoAaR0IAwrY=,iv:K+PQwl4SzKt3Ry2r0PQiakB9O6yvkf85BE+dH9mKQRQ=,tag:7uqJ/4BFVogKu0s8uba92w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
