apiVersion: v1
data:
    LD_DB_PASSWORD: ENC[AES256_GCM,data:HNNhsb2nhFvvYtGK1OSJMg==,iv:GmVU2akF9G8EdjXTrEYyLIHo25QvG/6bQoThY8ipdxk=,tag:6CsULSRavDPOmoquzZHAjA==,type:str]
    LD_DB_USER: ENC[AES256_GCM,data:QZPtLVt7yD4=,iv:UhJsAIh4hHyU08FZAJuSGC71SfHJzIt8a9W3a8ME/Ww=,tag:w+M2CwSZXZpU2l74dC4ZCg==,type:str]
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:8L7+fuvqr2q1zjW+,iv:/Z8fdxpKIFaIrRdzyALB9IVWOScqLo/SWDszFqNqLcA=,tag:EmgMg6NkedF2YAzDCjgGJQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:eu5MHw9B54IOuqb/yXHLPQ==,iv:pHXd839HKXYYZegjjzHhWjd+YML0+uEstwRdrcymrtQ=,tag:6nir5e327Em1U0eJb+sfcw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1c2eykwtau0ln8yxv6jdq5xl9fvnlh2ytcre3ctf5sx75dseag3pq6mmj4v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWDVQTFluL3poalM3T01z
            cFVIMmFkRjJnUGFZa2p5dWNGdkgvN2x0dWdNCkgrdHZCWjlsNnBIWXNVQUVpNUc3
            MGpzTVh5aFpxa29oanQvTmNXdVVCSXcKLS0tIFhzTDMrYW43OUx1MTd1d0JScXVn
            YWZKL1VyazlGR1RxYWhMWk85d0dYMFEKjSMoZeVazLjhq0WmLo7+d1cfkO+aMyw4
            O+BpyMqncsoLhTqQthm5L7blfzk2780OhMYmHS5R4YLzGFngMpc5fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-05T19:03:22Z"
    mac: ENC[AES256_GCM,data:h8I9mB/AR4rnyUk1U1YV5ZWIDKmpQfJ8CNoQ2hzUi6qt3FwCU0XCWuRF7c9W5jGQNj3yCtn2SpAyV3WA149URV/0MmcJ3A/lamyMOc0bRvF6bXYBXHqBOoGLXyV/T6f+A8fHmmcPk1x7NNH2xvvalm5qVtreUjMXzRGXI4un8Yg=,iv:PuJ8ULgXIcMqeyEGBvr6O1yC/NyRK1FhZga12QTKI3w=,tag:yCxKMnZoIoJXh5nF+KQBjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
