apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: RUNNER_SECRET
      remoteRef:
        key: forgejo-runner-secret
        property: RUNNER_SECRET
