apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-docker-cache
  namespace: forgejo-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
