apiVersion: v1
data:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:khoxj6sXm7SuOAUJ7Q/WBg==,iv:Da4pjjdSz9p5kln5G3GoDLLEhYw++VLGWFZLHHTj9go=,tag:UZ62nYBJS0U4H37jwI+nrA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pihole-container-env-secret
    namespace: pihole
sops:
    age:
        - recipient: age1c2eykwtau0ln8yxv6jdq5xl9fvnlh2ytcre3ctf5sx75dseag3pq6mmj4v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM2hLb3FqclFvV29ONFhY
            cU9HakJKTFNOWmRLSHNzamFsOWpBM3VIWjB3CnJEbWo3UFpRdnc2YUo3aE41MVVu
            RDQ5a2o4RmVWU3hPWDMzZ283YlMzM1EKLS0tIFF0bVVQdGhjUjZmbCsrVDB6Mlg1
            RTVIeURpR2gyMkE4eElPT2ZKN0xEbmsKzI7YjlCDRHdMdAmTTUC1N1ymVLcWq6N8
            gZfI0HHY2BkOTGzJN0oTVq557d4pIhMlgPtvTDUL2OXjilo6JS65qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T12:07:25Z"
    mac: ENC[AES256_GCM,data:0mCgRp8pN70WV/JY+k1GvZVzzprpto1SPop14DTPhOMSJEAjaz1xY67RjBDu0e+UdIM4WM3L4MT7VdRGlwg9N8l6RxLtKlqx03GMAsq2w+p4xfULvtUGuOmfn1F1thyz9VqBBOp1EBY68mSO+AQr6OcASva2qyx/mRGlegbbVsQ=,iv:xdpiCK67OvdobqUAMf8VR63sK56boDmVfXGaDTMxupQ=,tag:ohsOB360ZTqwYyzvGzbMtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
