apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: uclab-image-policy
spec:
  match:
    - group: apps
      version: v1
      resource: deployments
      name: uclab
  images:
    - glob: "forgejo.uclab.dev/affragak/uclab:*"
  authorities:
    - key:
        secretRef:
          name: cosign-pub-key
          namespace: cosign-system
