apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: uclab-image-policy
spec:
  images:
    - glob: "forgejo.uclab.dev/affragak/uclab**"
  authorities:
    - name: uclab
      key:
        secretRef:
          name: cosign-pub-key
          namespace: cosign-system
