apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: viewcounter-image-policy
spec:
  match:
    - resource: deployments
      group: apps
    - resource: replicasets
      group: apps
    - resource: pods
      version: v1
  images:
    - glob: "forgejo.uclab.dev/affragak/view-counter**"
  authorities:
    - name: uclab
      key:
        secretRef:
          name: cosign-pub-key
          namespace: cosign-system
