apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: viewcounter-image-policy
spec:
  images:
    match:
      - resource: pods
        version: v1
        selector:
          matchLabels:
            app: view-counter
      - glob: "forgejo.uclab.dev/affragak/view-counter**"
  authorities:
    - name: uclab
      key:
        secretRef:
          name: cosign-pub-key
          namespace: cosign-system
