[tools]
age = "latest"
cilium-cli = "latest"
cilium-hubble = "latest"
cosign = "latest"
direnv = "latest"
flux2 = "latest"
helm = "latest"
k9s = "latest"
kubectl = "1.32.1"
kubens = "latest"
pre-commit = "latest"
python = "3.13.9"
sops = "latest"
vault = "latest"
yq = "latest"


[hooks]
enter = "bash ./.devcontainer/scripts/setup_project"
