apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db-v1
spec:
  instances: 2

  # bootstrap:
  #   initdb:
  #     database: forgejodb
  #     owner: forgejo
  #     secret:
  #       name: forgejo-db-credentials

  bootstrap:
    recovery:
      database: forgejodb
      owner: forgejo
      source: source
      secret:
        name: forgejo-db-credentials

  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: forgejo-objectstore
          serverName: forgejo-db

  storage:
    size: 6Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: forgejo-objectstore
  monitoring:
    enablePodMonitor: true
