apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: forgejo-db-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth # CNPG prefers this type
  data:
    - secretKey: username
      remoteRef:
        key: forgejo-secrets/forgejo-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: forgejo-secrets/forgejo-db-credentials
        property: password
