apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: view-counter
resources:
  - ../../base/view-counter/
  - cloudflare-secret.yaml
  - cloudflare.yaml
  - forgejo-registry-secret.yaml
