apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: umami-uclab-tls
  namespace: umami
spec:
  secretName: umami-uclab-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - umami.uclab.dev
