apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosign-pub-key
  namespace: cosign-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: cosign-pub-key
    creationPolicy: Owner
  data:
    - secretKey: cosign.pub
      remoteRef:
        key: cosign-pub-key
        property: cosign.pub
