apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uclab
  namespace: uclab
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "22.2.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: uclab
      interval: 1m
  values:
    cloneStaticSiteFromGit:
      enabled: true
      repository: "https://gitlab.uclab8.net/affragak/uclab.git"
      branch: main
      gitClone:
        command:
          - /bin/bash
          - -ec
          - |
            [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source "/opt/bitnami/scripts/git/entrypoint.sh"
            git clone {{ .Values.cloneStaticSiteFromGit.repository }} --branch {{ .Values.cloneStaticSiteFromGit.branch }} /tmp/app
            [[ "$?" -eq 0 ]] && shopt -s dotglob && rm -rf /app/* && mv /tmp/app/* /app/

    serverBlock: |-
      server {
        listen 8080;
        root /app/public;
        index index.html;
      }
    service:
      type: ClusterIP
