apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db-v1
spec:
  instances: 2

  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-db-creds

  # bootstrap:
  #   recovery:
  #     database: app
  #     owner: app
  #     source: source
  #     secret:
  #       name: paperless-db-credentials
  #
  # externalClusters:
  #   - name: source
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: paperless-objectstore
  #         serverName: paperless-db-v1

  storage:
    size: 10Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: paperless-objectstore
  monitoring:
    enablePodMonitor: true
