apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db-creds
  namespace: paperless
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: paperless-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: paperless-db-creds
        property: username
    - secretKey: password
      remoteRef:
        key: paperless-db-creds
        property: password
