apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 1h
  chart:
    spec:
      chart: netbox
      version: "8.0.23"
      sourceRef:
        kind: HelmRepository
        name: netbox
        namespace: netbox
      interval: 12h

  valuesFrom:
    - kind: ConfigMap
      name: netbox-values
