apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: netbox-secret
    creationPolicy: Owner
    template:
  data:
    - secretKey: secretKey
      remoteRef:
        key: netbox/secretkey
        property: secretKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-superuser-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: netbox-superuser-secret
    creationPolicy: Owner
    template:
  data:
    - secretKey: superuserPassword
      remoteRef:
        key: netbox/superuserPassword
        property: superuserPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-postgresql-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: netbox-postgresql-secret
    creationPolicy: Owner
    template:
  data:
    - secretKey: password
      remoteRef:
        key: netbox/postgresqlPassword
        property: postgresqlPassword
    - secretKey: postgresPassword
      remoteRef:
        key: netbox/postgresqlPostgresPassword
        property: postgresqlPostgresPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-redis-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: netbox-redis-secret
    creationPolicy: Owner
    template:
  data:
    - secretKey: redisPassword
      remoteRef:
        key: netbox/redisPassword
        property: superuserPassword
