apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault

spec:
  releaseName: vault
  interval: 15m
  chart:
    spec:
      chart: vault
      version: 0.28.0
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault

  valuesFrom:
    - kind: ConfigMap
      name: vault-values
