apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: vault
spec:
  secretName: vault-server-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiration
  issuerRef:
    name: vault-issuer
    kind: Issuer
  commonName: vault.vault.svc.cluster.local
  dnsNames:
    # Internal headless service (for Raft communication)
    - vault-0.vault-internal
    - vault-1.vault-internal
    - vault-0.vault-internal.vault.svc.cluster.local
    - vault-1.vault-internal.vault.svc.cluster.local
    - "*.vault-internal"
    - "*.vault-internal.vault.svc.cluster.local"

    # Main service
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local

    # Active service
    - vault-active
    - vault-active.vault.svc.cluster.local

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
