apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-production-cnpg-v0
  namespace: linkding
spec:
  description: Postgres cluster for the linkding application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 2
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store
  monitoring:
    enablePodMonitor: true
  inheritedMetadata:
    labels:
      app: linkding-database
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: linkding
      owner: ladmin
      secret:
        name: linkding-db-creds
  # backup:
  #   barmanObjectStore:
  #     destinationPath: "s3://backups/"
  #     endpointURL: "http://atlas.uclab8.net:9000"
  #     s3Credentials:
  #       accessKeyId:
  #         name: minio-s3
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: minio-s3
  #         key: ACCESS_SECRET_KEY
  #     wal:
  #       compression: gzip
  #     data:
  #       compression: gzip
  #   retentionPolicy: 7d
  resources:
    requests:
      memory: 320Mi
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: linkding-db
            spec:
              type: ClusterIP
