apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-production-cnpg-v0
  namespace: linkding
spec:
  description: Postgres cluster for the linkding application
  imageName: quay.io/enterprisedb/postgresql:16.8
  instances: 2
  primaryUpdateStrategy: unsupervised
  backup:
  retentionPolicy: "3d"
  barmanObjectStore:
    destinationPath: "s3://backups/"
    s3Credentials:
      accessKeyId:
        name: minio-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio-s3
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store
  monitoring:
    enablePodMonitor: true
  inheritedMetadata:
    labels:
      app: linkding-database
  storage:
    size: 1Gi
    storageClass: synology-iscsi-storage
  bootstrap:
    initdb:
      database: linkding
      owner: affragak
      secret:
        name: linkding-db-creds
  resources:
    requests:
      memory: 320Mi
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: linkding-db
            spec:
              type: ClusterIP
