apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-production-cnpg-v0
  namespace: linkding
spec:
  description: Postgres cluster for the linkding application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 1
  monitoring:
    enablePodMonitor: true
  inheritedMetadata:
    labels:
      app: linkding-database
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: linkding
      owner: ladmin
      secret:
        name: linkding-db-creds
  resources:
    requests:
      memory: 320Mi
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: linkding-db
            spec:
              type: ClusterIP
