apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-env-container-db
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: umami-env-container-db
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: umami-env-container-db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: umami-env-container-db
        property: password
