provider:
  name: pihole
policy: sync

envFrom:
  - secretRef:
    name: pihole-password

extraArgs:
  - --pihole-server=http://pihole.pihole.svc.cluster.local/api
  - --pihole-api-version=6

# extraEnvVars:
#   - name: EXTERNAL_DNS_PIHOLE_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: pihole-password
#         key: password

sources:
  - ingress

ingressClassFilters:
  - cilium
