provider:
  name: pihole
policy: sync

env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: EXTERNAL_DNS_PIHOLE_PASSWORD

extraArgs:
  - --pihole-server=http://pihole.pihole.svc.cluster.local
  - --pihole-api-version=6
  - --gateway-label-filter=external-dns==enabled

# extraEnvVars:
#   - name: EXTERNAL_DNS_PIHOLE_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: pihole-password
#         key: password

sources:
  - gateway-httproute

ingressClassFilters:
  - cilium
