provider:
  name: pihole

policy: sync

pihole:
  server: http://pihole.pihole.svc.cluster.local
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password
ingressClassFilters:
  - cilium
