provider:
  name: pihole
policy: sync

env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: EXTERNAL_DNS_PIHOLE_PASSWORD

extraArgs:
  - --pihole-server=http://pihole.pihole.svc.cluster.local
  - --pihole-api-version=6

# extraEnvVars:
#   - name: EXTERNAL_DNS_PIHOLE_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: pihole-password
#         key: password

sources:
  - ingress
  - service
  - gateway-httproute
  - gateway-tlsroute
  - gateway-tcproute

ingressClassFilters:
  - cilium
