provider:
  name: pihole
policy: sync

extraArgs:
  - --pihole-server=http://pihole.pihole.svc.cluster.local
  # - --pihole-api-version=6

extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password

sources:
  - ingress

ingressClassFilters:
  - cilium
