apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mktxp-credentials
  namespace: mktxp
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: mktxp-credentials
    creationPolicy: Owner
  data:
    - secretKey: _mktxp.conf
      remoteRef:
        key: apps/mktxp-credentials
        property: _mktxp.conf
    - secretKey: mktxp.conf
      remoteRef:
        key: apps/mktxp-credentials
        property: mktxp.conf
