apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: umami-db
spec:
  instances: 2

  bootstrap:
    initdb:
      database: umami
      owner: umami
      secret:
        name: umami-db-creds

  # bootstrap:
  #   recovery:
  #     database: app
  #     owner: app
  #     source: source
  #     secret:
  #       name: umami-db-credentials
  #
  # externalClusters:
  #   - name: source
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: umami-objectstore
  #         serverName: umami-db-v1

  storage:
    size: 5Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: umami-objectstore
  monitoring:
    enablePodMonitor: true
