apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-counter
  namespace: view-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-counter
  template:
    metadata:
      labels:
        app: view-counter
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: view-counter
          image: forgejo.uclab.dev/affragak/view-counter@sha256:8660e663f7a6d4dd9fffc51ad9ee3ce4611f385f329c85a2ed19908106c48ea2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          ports:
            - containerPort: 9313
          envFrom:
            - configMapRef:
                name: viewcounter-configmap
            - secretRef:
                name: view-counter-container-env
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 9313
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 9313
            initialDelaySeconds: 5
            periodSeconds: 10
