apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-counter
  namespace: view-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-counter
  template:
    metadata:
      labels:
        app: view-counter
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: view-counter
          image: forgejo.uclab.dev/affragak/view-counter@sha256:fd251e27a57cbfa8308769ec4bd297e4fba38ffb78d3ff6109c3e8643f81346a
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          ports:
            - containerPort: 9313
          envFrom:
            - configMapRef:
                name: viewcounter-configmap
            - secretRef:
                name: view-counter-container-env
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 9313
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 9313
            initialDelaySeconds: 5
            periodSeconds: 10
