apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: view-counter-db-credentials
  namespace: view-counter
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: view-counter-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: view-counter-db
        property: username
    - secretKey: password
      remoteRef:
        key: view-counter-db
        property: password
