apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: hausarztpraxis
spec:
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
  interval: 24h
