apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - ../../base/forgejo/

patches:
  - patch: |
      apiVersion: postgresql.cnpg.io/v1
      kind: ScheduledBackup
      metadata:
        name: forgejo-db-backup
      spec:
        schedule: "0 0 4 * * *"
    target:
      kind: ScheduledBackup
      name: forgejo-db-backup

  - patch: |
      apiVersion: barmancloud.cnpg.io/v1
      kind: ObjectStore
      metadata:
        name: forgejo-objectstore
      spec:
        configuration:
          destinationPath: "s3://backups-staging/"
          retentionPolicy: 3d
    target:
      kind: ObjectStore
      name: forgejo-objectstore
