apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botkube-plugins-cache
  namespace: botkube
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-nfs-storage
