apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: botkube
  namespace: botkube

spec:
  releaseName: botkube
  interval: 15m
  chart:
    spec:
      chart: botkube
      version: 1.*
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: botkube

  valuesFrom:
    - kind: ConfigMap
      name: botkube-values
