apiVersion: v1
kind: Endpoints
metadata:
  name: ubuntu-server-metrics
  namespace: monitoring # adjust to your namespace
  labels:
    app: ubuntu-server
subsets:
  - addresses:
      - ip: 10.10.10.8 # Your Ubuntu server IP
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-server-metrics
  namespace: monitoring
  labels:
    app: ubuntu-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ubuntu-server
  namespace: monitoring
  labels:
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app: ubuntu-server
  endpoints:
    - port: metrics
      interval: 30s
