apiVersion: v1
kind: Endpoints
metadata:
  name: ubuntu-server-metrics
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.10.10.8
    ports:
      - name: http-metrics
        port: 9100
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-server-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: ubuntu-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ubuntu-server
  namespace: monitoring
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: ubuntu-server
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ubuntu-server
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
