apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret-key
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: paperless
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: paperless
        property: secret_key
