apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  name: pihole
spec:
  rules:
    - host: pihole.uclab8.net
      http:
        paths:
          - backend:
              service:
                name: docs
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - pihole.uclab8.net
      secretName: pihole-tls-staging
