apiVersion: v1
kind: Service
metadata:
  name: forgejo-ssh
  namespace: forgejo
spec:
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
  selector:
    app: forgejo
  type: LoadBalancer
