apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-cisco-credentials
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: snmp-cisco-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: snmp-cisco
        property: username
    - secretKey: auth_password
      remoteRef:
        key: snmp-cisco
        property: auth_password
    - secretKey: priv_password
      remoteRef:
        key: snmp-cisco
        property: priv_password
