apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-container-env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: linkding-container-env
    creationPolicy: Owner
  data:
    - secretKey: LD_SUPERUSER_NAME
      remoteRef:
        key: linkding-container-env
        property: LD_SUPERUSER_NAME
    - secretKey: LD_SUPERUSER_PASSWORD
      remoteRef:
        key: linkding-container-env
        property: LD_SUPERUSER_PASSWORD
    - secretKey: LD_DB_USER
      remoteRef:
        key: linkding-container-env
        property: LD_DB_USER
    - secretKey: LD_DB_PASSWORD
      remoteRef:
        key: linkding-container-env
        property: LD_DB_PASSWORD
