apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: blog-uclab8
    app.kubernetes.io/name: nginx
  name: nginx-server-block
  namespace: blog
data:
  default.conf: |-
    server {
      listen 80;
      location / {
        root   /www/public;
        index  index.html;
      }
    }
