apiVersion: v1
kind: ConfigMap
metadata:
  name: syslog-ng-config
data:
  syslog-ng.conf: |
    @version: current
    @include "scl.conf"
    source s_local {
    internal();
    };

    source s_network {
    default-network-drivers(
    );
    };
    template t_promtail_rfc5424 {
        template("<${PRI}>1 ${ISODATE} ${HOST} ${PROGRAM} ${PID} ${MSGID} - ${MSG}\\n");
    };

    destination d_loki {
       syslog("promtail-syslog.monitoring.svc.cluster.local" transport("tcp") port(1514)
       template(t_promtail_rfc5424)
       );
    };
    log {
        source(s_local);
        source(s_network);
        destination(d_loki);
    };
