apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-container-env-secret
  namespace: pihole
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: pihole-container-env-secret
    creationPolicy: Owner
  data:
    - secretKey: FTLCONF_webserver_api_password
      remoteRef:
        key: pihole-container-env-secret
        property: FTLCONF_webserver_api_password
